name: Testomatio Tests

on:
  workflow_dispatch:
    inputs:
      grep:
        description: "tests to grep "
        required: false
        default: ""
      run:
        required: false
      testomatio:
        required: false

jobs:
  run-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install chromium
      - name: Run type checks
        run: npx tsc -p tsconfig.json --noEmit
      - name: Run Playwright tests
        run: npx playwright test --grep "${{ github.event.inputs.grep }}"
        env:
          TESTOMATIO: "${{ github.event.inputs.testomatio }}"
          TESTOMATIO_RUN: "${{ github.event.inputs.run }}"
    # - uses: actions/upload-artifact@v4
    #   if: ${{ !cancelled() }}
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 10
    # - name: Publish Test Report
    #   uses: ctrf-io/github-test-reporter@v1
    #   with:
    #     report-path: './ctrf/*.json'
    #   if: always()
